server {
    listen 80;

    include /etc/nginx/mime.types;

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        # Esto es importante para las Single Page Applications (React/Vite)
        try_files $uri $uri/ /index.html;
    }
}
